### PR TITLE
Typos, doc clarifications

### PR DESCRIPTION
**Pull request by MarkHerhold**

### CODE REVIEW

**Comment by evangboucher** [comment]
Pull requests will currently not work as TravisCI encrypted environment keys are specific to the repository they were created for (evangboucher/DynaDoc). So forking will not work in the current setup. 

I am looking into a potential solution.

**Comment by evangboucher** [comment]
So one idea is that you could use your own AWS user credentials in the .travis.yml for your fork. Make sure you do not attempt to commit the .travis.yml (ignore it). The AWS IAM user you create should have full access to DynamoDB. 

The three env variables you will need to set are below (do not wrap with quotations):

accessKeyId=YOUR_ACCESS_KEY_ID
secretAccessKey=YOUR_SECRET_ACCESS_KEY
region=YOUR_REGION_OF_CHOICE

Set the region to an AWS region of your choice. Ex: us-east-1

The reasons for this issue are located in this article: 
https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests

Details on how to encrypt environment variables for TravisCI can be found in this article: 
https://docs.travis-ci.com/user/environment-variables/

For now try that, and see if it will work. :) Let me know if you encounter any issues or have any better ideas!

**Comment by MarkHerhold** [comment]
I am a lazy person and am only delivering doc changes. They should be
either accepted or rejected. The fact that CI isn't working in this
scenario is not my concern. :)

**Comment by evangboucher** [comment]
lol, well I appreciate the changes. I will force them through, but feel free to try the suggested fix should you wish to change a source document. :) 

Thanks for your help!

**Pull request merged**
